# version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
